service: personal-details-section

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1

functions:
  personal:
    handler: personal.handler
    events:
      - http:
          path: personal
          method: any
          cors: true

  presentAddress:
    handler: presentAddress.handler
    events:
      - http:
          path: presentAddress
          method: any
          cors: true

  permanentAddress:
    handler: permanentAddress.handler
    events:
      - http:
          path: permanentAddress
          method: any
          cors: true

  languages:
    handler: languages.handler
    events:
      - http:
          path: languages
          method: any
          cors: true

  additional_info1:
    handler: additional_info1.handler
    events:
      - http:
          path: additional_info1
          method: any
          cors: true

  additional_info2:
    handler: additional_info2.handler
    events:
      - http:
          path: additional_info2
          method: any
          cors: true

  SocialProfile:
    handler: SocialProfile.handler
    events:
      - http:
          path: socialProfile
          method: any
          cors: true

  login:
    handler: login.handler
    events:
      - http:
          path: login
          method: any
          cors: true

package:
  include:
    - node_modules/**
  exclude:
    - tests/**
    - .git/**
    - .serverless/**

plugins:
  - serverless-offline
